
* Définir des chantiers de la transition écologique permettant de qualifier des métiers

France Nation Verte a vocation à couvrir les enjeux environnementaux principaux, et fournissent un cadre d'analyse ancré dans les politiques publiques, qui se veut cohérent. Dans ce cadre, on peut définir les métiers "stratégiques pour la transition écologique" comme les métiers qui ont une contribution significative à au moins un des chantiers de la planification écologique.

Limites :
- les actions et chantiers vont continuer à évoluer et à se préciser (notamment pour la famille Mieux consommer, et pour les volets adaptation, santé, ressources, gouvernance)
- en alignant des chantiers sans préciser leur potentiel de contribution à un tout limite la capacité à faire sortir le plus saillant (les métiers les plus à risques ou les métiers les plus stratégiques) mais on ne dispose pas d'une métrique unique permettant de le faire (carbone non suffisant)
- la classification en 52 leviers de décarbonation ne peut convenir :
  - ce sont des leviers de décarbonation, sujets de ressources ou de nature sont peu présents
  - ils sont peu opérationnalisés pour parler de l'emploi : si "Résidentiel fioul" est parlant pour voir comment on abat 9 Mt d'émissions entre 2019 et 2030, il n'y a pas une évolution positive (à mettre en avant) des compétences / des gestes métiers, de nouveaux métiers ou de la demande de travail sur le marché du travail (cf revue de littérature).

* Méthodologie

** Cadre
Le suivi des métiers stratégiques pour la planification écologique par le SGPE se place dans un cadre avec la méthode de référence utilisée dans [cite:@diagne2023_reb_2030] :

1) À partir d'une revue bibliographique (EDEC de la branche Constructys notamment) et des entretiens auprès des acteurs de la filière (Opco, fédérations professionnelles, OS, entreprises, RCO, OF, etc.), construit une liste de métiers "de la rénovation énergétique des bâtiments". Celle-ci a été déclinée dans les nomenclatures ROME, FAP, PCS.

2) En croisant la liste des PCS retenue et les secteurs d'activité (NAF) correspondant à la Construction et aux activités d'ingénierie et d'architecture, on ne retient que les personnes qui exercent les métiers définis en étape (1) dans les entreprises de la filière.

Ce croisement ne permet pour le moment de ne donner qu'une estimation du vivier. L'étape (2) et son amélioration (en termes de fiabilité, voir note à la fin sur la DSN) relèvent du travail du SGPE / DARES / INSEE / France Stratégie.

Ce travail se veut être un appui pour améliorer et définir des catégories pour un suivi statistique dans le temps de métiers stratégiques pour la planification écologique (étape 1), s'appuyant sur les travaux existants des différents EDEC, études de branches, diagnostics d'AMI-CMA.

** Maille des chantiers

Dans les travaux sur la base O•NET, les impacts attendus de la transition écologique sur les emplois sont de trois natures [cite:@dierdorff2009_greening_work]:
- adaptation des compétences / tâches
- émergence de métiers nouveaux
- évolution de la demande en emplois

La maille des chantier qui semble la plus pertinente est celle qui permet /a minima/ de saisir ces phénomènes au niveau des métiers [cite:@consoli2016_do]. En particulier, il semble difficile de se satisfaire d'une maille "50 sites" et "industrie diffuse" pour parler de métiers et de compétences.

** Définition des chantiers

Rentrer dans les chantiers / actions / leviers en précisant progressivement, et s'arrêter, pour chaque chantier, à  la maille décrite juste au-dessus.

1) Pour partir d'une base qui n'est pas uniquement centrée sur les leviers de décarbonation, partir des 22 leviers opérationnels et des 7 leviers transversaux de France Nation Verte  [cite:@pm2022_france_nation_verte]
2) Ajouter toutes les actions détaillées dans le plan France Nation Verte [cite:@sgpe2023_france_nation_verte]
3) Ajouter des chantiers "directs", en partant assez directement des actions détaillées pour synthétiser un chantier.
4) Harmonisation : utilisation des mêmes verbes d'actions et de périmètre pour les différents chantiers (non terminé).
5) Partage / retours / raffinements (le versionnage permet la transparence sur ce qui change).

** Problèmes restants à lever, prochaines étapes

- Reprendre le versionnage pour expliciter les étapes de la méthodo de manière plus transparente.

- Pour faire des recommandations de taggage au niveau national, il y a un enjeu à expliciter les choix faits pour certaines données très localisées (typiquement la décarbonation des 50 sites industriels). Première intuition : les "50 sites" le sont pour des raisons de taille, mais certainement avant tout de process industriels. Peu de raisons que pour les mêmes process industriels, on ait moins d'émissions dans d'autres sites, qui sont peut-être juste moins importants en taille. Quand bien même ils ne seraient pas directement dans les 50 sites en question, le fait qu'un métier contribue à l'évolution des process industriels en question devrait pouvoir suffire pour le qualifier de métier stratégique pour la transition écologique.

  TODO Est-ce que les 50 sites industriels rentrent tous dans les leviers de décarbonation de l'ensemble de l'industrie (DGE) https://www.entreprises.gouv.fr/fr/publication-contrats-transition-ecologique-50-sites-industriels . Si oui => On peut faire rentrer le levier 50 sites en détaillant les leviers de la transition écologique dans les feuilles de route de décarbonation strictement.

- Les chantiers transversaux ne sont pas directs, se retrouvent dans plusieurs leviers. Besoin d'un peu plus de travail pour s'assurer d'une prise en compte pertinente.

- Aujourd'hui, la DSN serait la meilleure source pour quantifier le vivier réel (données actualisées disponibles en « temps réel ») de travailleurs mais :
  - Son exploitation est encore complexe (l'exploitation statistique n'était pas une finalité d'usage à sa création)
  - Elle n'est bien renseignée que pour les salariés (pour l'instant), or un volume assez important de travailleurs du bâtiment est à son compte et échappe donc à cette DSN.
  - Il n'y a pas encore de table de passage entre la PCS-ESE dans la DSN et la PCS2020, donc impossible de recouper notre liste avec les métiers renseignés dans la DSN, sauf à le faire à la main...
